Add EventHub emulation

diff --git a/azure-pipelines/templates/test-node-version.yml b/azure-pipelines/templates/test-node-version.yml
--- a/azure-pipelines/templates/test-node-version.yml
+++ b/azure-pipelines/templates/test-node-version.yml
@@ -11,11 +11,17 @@ steps:
           versionSpec: ${{ parameters.nodeVersion }}
       displayName: 'Install Node ${{ parameters.nodeVersion }}'
       retryCountOnTaskFailure: 10
-    - task: AzureCLI@2
+    - bash: |
+        docker compose -f src/utils/eventhub/docker-compose.yml pull
+        docker compose -f src/utils/eventhub/docker-compose.yml up -d
+      displayName: 'Install Azurite and Start EventHub Emulator'
+    - bash: |
+        echo "Waiting 20s for EventHub Emulator to boot..."
+        sleep 20
+        echo "=== EventHub Emulator Logs ==="
+        docker logs eventhubs-emulator || echo "Failed to get emulator logs"
+      displayName: 'Output EventHub Emulator Logs'
+    - bash: |
+        npm run ${{ parameters.testCommand }}
       displayName: 'Run tests Node ${{ parameters.nodeVersion }}'
       continueOnError: true
-      inputs:
-          azureSubscription: 'SimpleBatchNodeE2ESC'
-          scriptType: 'bash'
-          scriptLocation: 'inlineScript'
-          inlineScript: 'npm run ${{ parameters.testCommand }}'
